### ISSUE TITLE
OSX install script

### ISSUE THREAD

**Issue by ojczeo** [google-coral/project-bodypix#6]
Hello, 
have anybody tried to run this project on OSX? As far as I can see it uses libraries that are available on Mac Os, but unfortunately, I can't go through the installation, I've tried to modify `install_requirements.sh` to meet OSX, but without success.

**Comment by Namburger** [comment]
@ojczeo what exact issue do you have?
I believe that it is possible, but the gstreamer pipeline were written specifically for generic linux and highly optimized for the dev board. I may be able to help if I can get more info on the failures

**Comment by ojczeo** [comment]
this is my script:
```bash
echo "Installing DevBoard specific dependencies"
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p $HOME/miniconda
brew install python3-pip python3-scipy 
# brew install pygobject3
conda install -c pkgw-forge gtk3
sudo pip3 install svgwrite
sudo pip3 install python-periphery 
```
The error I've get after running: `python3 bodypix.py`
```log
Traceback (most recent call last):
  File "bodypix.py", line 28, in <module>
    import gstreamer
  File "/Users/andrzej/projekty/google-project-bodypix/gstreamer.py", line 20, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by Namburger** [comment]
@ojczeo Ahh, I see, this is a pure installation problem. Basically, our installation script assumes that you are running in a linux machine with [apt package manager](https://github.com/google-coral/project-bodypix/blob/master/install_requirements.sh#L23). 
I don't have a MAC to test, but it seems that 
```
ModuleNotFoundError: No module named 'gi'
```
is a generic python module issue. You may find some better info [here](https://stackoverflow.com/questions/18119618/importerror-no-module-named-gi-repository-mac-os-x)?

**Comment by manoj7410** [comment]
@ojczeo Is this issue still reproducible ?

**Comment by manoj7410** [comment]
Closing this due to lack of activity. Feel free to reopen if this is still reproducible.
